# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=250, null=True)),
                ('post_type', models.CharField(choices=[(b'0', b'image'), (b'1', b'text')], max_length=1, null=True)),
                ('text_or_url', models.CharField(max_length=2000, null=True)),
                ('site', models.CharField(choices=[(b'0', b'facebook'), (b'1', b'twitter')], max_length=1, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_type', models.CharField(choices=[(b'0', b'Offensive'), (b'1', b'Adult'), (b'2', b'Racy'), (b'3', b'Mature')], max_length=1, null=True)),
                ('count', models.IntegerField(default=0)),
                ('site', models.CharField(choices=[(b'0', b'facebook'), (b'1', b'twitter')], max_length=1, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(blank=True, max_length=250, unique=True)),
                ('no_of_post', models.IntegerField(default=0)),
                ('site', models.CharField(choices=[(b'0', b'facebook'), (b'1', b'twitter')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=250)),
                ('post_category', models.CharField(choices=[(b'0', b'i_to_a'), (b'1', b't_to_a')], max_length=1, null=True)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('tagname', models.CharField(max_length=100, null=True)),
                ('site', models.CharField(choices=[(b'0', b'facebook'), (b'1', b'twitter')], max_length=1, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=250)),
                ('tag_type', models.CharField(choices=[(b'0', b'generic'), (b'1', b'account')], max_length=1, null=True)),
                ('site', models.CharField(choices=[(b'0', b'facebook'), (b'1', b'twitter')], max_length=1, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
