# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
    ]
