# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='valid_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
