# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0002_usertag_valid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='valid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
