# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0003_auto_20180305_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='valid_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
