# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0003_auto_20171104_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
