# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('null', '0004_auto_20180303_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=250, null=True)),
                ('post_type', models.CharField(choices=[(b'0', b'image'), (b'1', b'url')], max_length=1, null=True)),
                ('text_or_url', models.CharField(max_length=2000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_type', models.CharField(choices=[(b'0', b'Obscene'), (b'1', b'Adult'), (b'2', b'Racy'), (b'3', b'Other')], max_length=1, null=True)),
                ('count_0', models.IntegerField(default=0)),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
                ('count_3', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(blank=True, max_length=250, unique=True)),
                ('no_of_post', models.IntegerField(default=0)),
            ],
        ),
    ]
