# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('null', '0006_auto_20180303_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='stats',
            name='sentiment_type',
            field=models.CharField(choices=[(b'0', b'Obscene'), (b'1', b'Adult'), (b'2', b'Racy'), (b'3', b'Other'), (b'4', b'Piyush')], max_length=1, null=True),
        ),
    ]
