# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0007_auto_20180304_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertag',
            old_name='tagname',
            new_name='postid',
        ),
        migrations.AddField(
            model_name='usertag',
            name='post_category',
            field=models.CharField(choices=[(b'0', b'i_to_a'), (b'1', b't_to_a')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='sentiment_type',
            field=models.CharField(choices=[(b'0', b'Offensive'), (b'1', b'Adult'), (b'2', b'Racy'), (b'3', b'Mature')], max_length=1, null=True),
        ),
    ]
