# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('null', '0008_auto_20180304_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=250)),
                ('post_category', models.CharField(choices=[(b'0', b'i_to_a'), (b'1', b't_to_a')], max_length=1, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='usertag',
            old_name='postid',
            new_name='tagname',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='post_category',
        ),
        migrations.AddField(
            model_name='usertag',
            name='tag_type',
            field=models.CharField(choices=[(b'0', b'generic'), (b'1', b'account')], max_length=1, null=True),
        ),
    ]
