# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0010_userpost_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='tagname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
